# Generated by Django 2.0.13 on 2020-01-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('cor', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='publish_date',
            new_name='data_publicacao',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='text',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='created_date',
        ),
        migrations.AddField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Area'),
        ),
    ]
