# Generated by Django 2.0.13 on 2020-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200120_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
